first pass adding a benchmark workflow

diff --git a/.github/workflows/macosx_windows_ci.yaml b/.github/workflows/macosx_windows_ci.yaml
--- a/.github/workflows/macosx_windows_ci.yaml
+++ b/.github/workflows/macosx_windows_ci.yaml
@@ -73,3 +73,84 @@ jobs:
         with:
           token: ${{secrets.CODECOV_TOKEN}} #required
           file: ./coverage.xml #optional
+  benchmark:
+    name: Performance Benchmark
+    needs: tests
+    env:
+      PYTHON: ${{ matrix.python-version }}
+    runs-on: ${{ matrix.os }}
+    defaults:
+     run:
+       # Adding -l {0} helps ensure conda can be found properly in windows.
+       shell: bash -l {0}
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [macos-latest, windows-latest, ubuntu-latest]
+        python-version: ["3.12"]
+        include:
+          - env_name: pyuvdata_tests_windows
+            os: windows-latest
+          - env_name: pyuvdata_tests_mac_arm
+            os: macos-latest
+          - env_name: pyuvdata_tests
+            os: macos-13
+            python-version: "3.12"
+          - env_name: pyuvdata_test
+            os: ubuntu-latest
+    steps:
+      - uses: actions/checkout@main
+        with:
+          fetch-depth: 0
+
+      - name: Setup Minimamba
+        uses: conda-incubator/setup-miniconda@v3
+        with:
+          miniforge-variant: Mambaforge
+          miniforge-version: latest
+          use-mamba: true
+          python-version: ${{ matrix.python-version }}
+          environment-file: ci/${{ matrix.env_name }}.yml
+          activate-environment: ${{ matrix.env_name }}
+          run-post: false
+
+      - name: Conda Info
+        run: |
+          conda info -a
+          conda list
+          PYVER=`python -c "import sys; print('{:d}.{:d}'.format(sys.version_info.major, sys.version_info.minor))"`
+          if [[ $PYVER != $PYTHON ]]; then
+            exit 1;
+          fi
+
+      # also install benchmark utility
+      - name: Install
+        run: |
+          pip install pytest-benchmark
+          pip install .
+
+      - name: Run benchmark
+        run: |
+          pytest --benchmark-only --benchmark-json output.json
+
+      # Download previous benchmark result from cache (if exists)
+      - name: Download previous benchmark data
+        uses: actions/cache@v4
+        with:
+          path: ./cache
+          key: ${{ runner.os }}-benchmark
+
+      # Run `github-action-benchmark` action
+      - name: Store benchmark result
+        uses: benchmark-action/github-action-benchmark@v1
+        with:
+          # What benchmark tool the output.txt came from
+          tool: 'pytest'
+          # Where the output from the benchmark tool is stored
+          output-file-path: output.json
+          # Where the previous data file is stored
+          external-data-json-path: ./cache/benchmark-data.json
+          # Workflow will fail when an alert happens
+          fail-on-alert: true
+          # Enable Job Summary for PRs
+          summary-always: true
